
image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - production
  - dev

production:
  stage: production
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_DEV --api-key=$HEROKU_API_KEY
  only:
    - master

dev:
  stage: dev
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_DEV --api-key=$HEROKU_API_KEY
  only:
    - dev
